config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  namespace :api, defaults: { format: :json } do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end

  devise_for :users
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/User.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes
  has_many :comments

  def three_most_recent_posts
    posts.limit(3)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :posts, foreign_key: 'author_id', dependent: :delete_all
  has_many :likes, foreign_key: 'author_id', dependent: :delete_all
  has_many :comments, foreign_key: 'author_id', dependent: :delete_all
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.limit(3)
  end

  def admin?
    @role = 'admin'
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  before_action :authorize_request
  skip_before_action :authenticate_user!
  include Response
  def index
    @users = User.all
    if @users.empty?
      json_response({ res: 'No users' })
    else
      render json: @users
    end
  end

  def show
    render json: User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def show
    @posts = @user.three_most_recent_posts
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo, :bio)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<%= link_to "Home", root_path, class: "home-btn"  %>
<h1 class="main-heading">All the users</h1>
<div class="main-container">
  <% @users.each do |user| %>
    <div class="flexd">
      <%= render 'shared/user', obj: user %>
      <%= link_to "View profile", user_path(user.id), class: "view-profile"   %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= link_to "Back", users_path, class: "back-btn" %>
<div class="show-user-container">
  <%= render '/shared/user', obj: @user %>
  <div class="user-bio">
    <p>Bio</p>
    <p> <%= @user.bio %> </p>
  </div>
  <% post = Post.new %>
  <% post.author = @user %>
  <% if can? :create, post %>
    <div class="create-post">
      <%= link_to 'Create post', new_user_post_path(@user.id)  %>
    </div>
  <% end %>
  <% if @posts.length > 0 %>
    <div class="user-posts">
      <% @posts.each_with_index do|post, index| %>
        <%= render '/shared/post', obj: post, idx: index, details: false %>
      <% end %>
    </div>
  <% else %>
    <p class="no-posts" >This user has no posts yet.</p>
  <% end %>
  <% if @user.posts_counter > 0 %>
    <%= link_to 'Show all posts', user_posts_path(@user) %>
  <% end %>
</div>