config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  namespace :api, defaults: { format: :json } do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end

  devise_for :users
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/Comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comment_counter

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/Like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/Post.rb
class Post < ApplicationRecord
  after_save :update_post_counter
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5)
  end
end

app/models/User.rb
class User < ApplicationRecord
  has_many :posts
  has_many :likes
  has_many :comments

  def three_most_recent_posts
    posts.limit(3)
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    case user&.role
    when 'admin'
      can :manage, :all
    when 'user'
      can :update, Post do |post|
        post.author == user
      end
      can :destroy, Post do |post|
        post.author == user
      end
      can :update, Comment do |comment|
        comment.author == user
      end
      can :destroy, Comment do |comment|
        comment.author == user
      end
      can :create, Post do |post|
        post.author == user
      end
      can :create, Comment
      can :create, Like
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :update_comment_counter
  after_destroy :decrement_comment_counter
  validates :text, presence: true, length: { maximum: 250 }

  def update_comment_counter
    post.increment!(:comments_counter)
  end

  def decrement_comment_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post
  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_post_counter
  after_destroy :decrement_post_counter
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  validates :title, presence: true, length: { maximum: 100 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def decrement_post_counter
    author.decrement!(:posts_counter)
  end

  def recent_comments
    comments.limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :posts, foreign_key: 'author_id', dependent: :delete_all
  has_many :likes, foreign_key: 'author_id', dependent: :delete_all
  has_many :comments, foreign_key: 'author_id', dependent: :delete_all
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def three_most_recent_posts
    posts.limit(3)
  end

  def admin?
    @role = 'admin'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new
    @like.author_id = params[:user_id]
    @like.post_id = params[:post_id]
    flash[:notice] = 'Post liked' if @like.save
    redirect_to user_post_path(params[:user_id], params[:post_id])
  end

  private

  def comment_params
    params.require(:like).permit(:text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource only: %i[edit update destroy create]
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author: params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_params)
    @post.author_id = params[:user_id]
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_path(params[:user_id])
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    return unless @post.destroy

    flash[:success] = 'Post deleted successfully'
    redirect_to user_posts_path
  end

  def user_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def show
    @posts = @user.three_most_recent_posts
  end

  private

  def user_params
    params.require(:user).permit(:name, :photo, :bio)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogWithRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| %>
      <p class="notification"> <%= msg %> </p>
    <%end%>
    <%= yield %>
  </body>
</html>

app/views/shared/_comments.html.erb
<div class="comments">
  <h4>Comments:</h4>
  <% comments.each do |comment| %>
    <div class="each-comment">
      <span> <%= comment.author.name %>: </span>
      <span> <%= comment.text %> </span>
      <% if can? :destroy, comment %>
        <%= button_to "Delete", user_post_comment_path(comment.author.id, comment.post.id, comment.id), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_post.html.erb
<div class="each-post">
  <div class="each-post-heading">
    <p class="post-num">Post  #<%= idx+1 %>: <%= obj.title%> </p>
    <p> <%= obj.text.length > 80 ? obj.text.first(80) + '...' : obj.text %> </p>
    <%= link_to ('View post ' + (idx+1).to_s) , user_post_path(@user.id, obj.id), class: "view-post"  %>
  </div>
  <div class="post-interactions">
    <span>Comments: <%= obj.comments_counter %>, </span>
    <span> Likes: <%= obj.likes_counter %> </span>
  </div>
  <% if details && comments.length > 0 %>
    <%= render '/shared/comments', comments: comments %>
  <% end %>
</div>

app/views/shared/_user.html.erb
<div class="user-card">
  <div class="image-container">
    <img src= <%= obj.photo %> alt="d-Image">
  </div>
  <div class="user-details">
    <h2> <%= obj.name %>  </h2>
    <p>Number of posts: <%= obj.posts_counter %></p>
  </div>
</div>