config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  namespace :api, defaults: { format: :json } do
    resources :users, only: %i[index show] do
      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end

  devise_for :users
  resources :users do
    resources :posts do
      resources :comments
      resources :likes
    end
  end
end

app/models/Post.rb
class Post < ApplicationRecord
  after_save :update_post_counter
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.limit(5)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  after_save :update_post_counter
  after_destroy :decrement_post_counter
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :delete_all
  has_many :likes, dependent: :delete_all
  validates :title, presence: true, length: { maximum: 100 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def decrement_post_counter
    author.decrement!(:posts_counter)
  end

  def recent_comments
    comments.limit(5)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  before_action :authorize_request
  skip_before_action :authenticate_user!
  include Response
  def index
    @posts = Post.where(author_id: params[:user_id])

    if @posts.empty?
      json_response({ res: 'No posts found' })
    else
      render json: @posts
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # load_and_authorize_resource only: %i[edit update destroy create]
  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author: params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_params)
    @post.author_id = params[:user_id]
    if @post.save
      flash[:notice] = 'Post created successfully'
      redirect_to user_path(params[:user_id])
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    return unless @post.destroy

    flash[:success] = 'Post deleted successfully'
    redirect_to user_posts_path
  end

  def user_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="errors">
    <h2>THe following errors prevented the post from being saved</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li> <%= message %> </li>
      <% end %>
    </ul>
  </div>
<%end%>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true do |f| %>
  <div class="devise-form">
    <div class="field">
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :text %><br/>
      <%= f.text_area :text, cols: 20, rows: 10 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= link_to "Back", user_path(@user), class: "back-btn" %>
<section class="posts-section">
  <%= render '/shared/user', obj: @user %>
  <% if @posts.length > 0 %>
    <div class="user-posts">
      <% @posts.each_with_index do|post, index| %>
        <%= render '/shared/post', obj: post, idx: index, comments: post.recent_comments, details: true %>
      <% end %>
    </div>
  <% else %>
    <p class="no-posts" >This user has no posts yet.</p>
  <% end %>
</section>
<p></p>

app/views/posts/new.html.erb
<h2>Create a new post</h2>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= link_to "Back", user_posts_path, class: "back-btn" %>
<div class="container">
  <div class="each-post">
    <div class="flex">
      <div class="post-heading">
        <p class="post-num">Post  By: <span class="post-user"><%= @user.name %></span> </p>
      </div>
      <div class="post-interactions">
        <span>Comments: <%= @post.comments_counter %>, </span>
        <span> Likes: <%= @post.likes_counter %> </span>
      </div>
    </div>
    <div class="title-like">
      <h4>Title:  <%= @post.title %> </h4>
      <% if can? :create, Like %>
        <%= button_to "Like", user_post_likes_path(@user.id, @post.id), method: :post %>
      <% end %>
    </div>
    <p class="post-text"> <%= @post.text  %> </p>
    <% if can? :destroy, @post %>
      <%= button_to 'Delete Post', user_post_path(@user.id, @post.id), method: :delete  %>
    <%end%>
    <% if @post.comments.length > 0 %>
      <%= render '/shared/comments', comments: @comments %>
    <% else %>
      <p class="no-posts" >No comments yet</p>
    <% end %>
  </div>
</div>
<div class="comment-form">
  <h3>Create new comments</h3>
  <%= form_with model: @comment, url: user_post_comments_path(current_user.id, @post.id), method: :post, local: true do |f| %>
    <p>
      <%= f.label :text %>
      <br/>
      <%= f.text_area :text, required: true, cols: 50, rows: 6 %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>